[project]
name = "backend"
version = "0.1.0"
description = "A django-ninja backend template"
dependencies = [
    "uwsgi; platform_system != 'Windows'",
    "pick",
    "rich",
    "ipython",
    "django-ninja",
    "django-extensions",
    "django>=3.0",
    "arrow",
    "PyJWT",
    "django-cors-headers",
    "mysqlclient",
    "cryptography",
    "requests",
    "redis==4.6.0",
    "types-redis~=4.6.0",
    "loguru",
    "django-constance",
    "django-print-sql",
]
readme = "README.md"
requires-python = ">= 3.10"

[tool.setuptools.packages.find]
include = ["backend", "backend.*"]

[tool.ruff]
extend-exclude = ["backend/apps/*/migrations"]
line-length = 160
target-version = "py310"

[tool.ruff.lint]
extend-select = [
    "A",    # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "B006", #https://docs.astral.sh/ruff/rules/mutable-argument-default/
    "I",    #https://docs.astral.sh/ruff/rules/#isort-i
    "INP",  #https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp
    "UP",   #https://docs.astral.sh/ruff/rules/#pyupgrade-up
]
ignore = [
    "F401", # https://docs.astral.sh/ruff/rules/unused-import/
    "E402", # https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/
]

[tool.uv.pip]
index-url = "https://mirrors.aliyun.com/pypi/simple/"
