[project]
name = "backend-template"
version = "0.1.0"
description = "A django-ninja backend template"
dependencies = [
    "uwsgi; platform_system != 'Windows'",
    "pick",
    "django-ninja",
    "django-extensions",
    "django>=3.0",
    "arrow",
    "PyJWT",
    "django-cors-headers",
    "mysqlclient",
    "cryptography",
    "requests",
    "redis==4.6.0",
    "loguru",
    "django-constance",
]
readme = "README.md"
requires-python = ">= 3.10"

[tool.ruff]
line-length = 160
target-version = "py310"

[tool.ruff.lint]
ignore = [
    "F401", # unused-import
    "E402", # module-import-not-at-top-of-file
]

[[tool.rye.sources]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
[[tool.rye.sources]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
[[tool.rye.sources]]
name = "pypi"
url = "https://pypi.org/simple/"

[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "rich",
    "ipython",
    "types-redis~=4.6.0",
    "ruff",
    "uv",
    "django-print-sql",
]

[tool.rye.scripts]
start = "python manage.py runserver"
makemigrations = "python manage.py makemigrations"
migrate = "python manage.py migrate"
tail = "python watch_log.py"
shell = """python manage.py shell_plus \
--ipython \
--print-sql \
--dont-load auth \
--dont-load admin \
--dont-load contenttypes \
--dont-load sessions"""
